//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StocksVisualizerUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEXSector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEXSector()
        {
            this.MEXSectorDatas = new HashSet<MEXSectorData>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SectorAssetClassId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEXSectorData> MEXSectorDatas { get; set; }
    }
}
