//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StocksVisualizerUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks_V
    {
        public long StockID { get; set; }
        public string Symbol { get; set; }
        public string Company { get; set; }
        public string Sector { get; set; }
        public string Exchange { get; set; }
        public string Industry { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> LastUpdated_MinData { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<long> MarketCap { get; set; }
        public Nullable<System.DateTime> Last_Updated_MC { get; set; }
        public Nullable<System.DateTime> MostRecent_Stats { get; set; }
        public Nullable<System.DateTime> MostRecent_DailyData { get; set; }
    }
}
