//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StocksVisualizerUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.HistoricalDatas = new HashSet<HistoricalData>();
            this.MarketCapitalizations = new HashSet<MarketCapitalization>();
            this.MinuteDatas = new HashSet<MinuteData>();
            this.MinuteDataTesters = new HashSet<MinuteDataTester>();
            this.SampleStats = new HashSet<SampleStat>();
        }
    
        public long ID { get; set; }
        public string Symbol { get; set; }
        public string Company { get; set; }
        public string Exchange { get; set; }
        public string Industry { get; set; }
        public string Description { get; set; }
        public string IssueType { get; set; }
        public Nullable<long> SectorID { get; set; }
        public Nullable<int> Employees { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> LastUpdated_MinData { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<decimal> PercentData_LastDay { get; set; }
        public Nullable<decimal> PercentData_SamplePeriod { get; set; }
        public Nullable<bool> IsTop4000 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoricalData> HistoricalDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketCapitalization> MarketCapitalizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MinuteData> MinuteDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MinuteDataTester> MinuteDataTesters { get; set; }
        public virtual Sector Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleStat> SampleStats { get; set; }
    }
}
